version: '3.1'

services:
  app:
    build:
      context: "."
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: balance
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd